io.popen "doskey ls=dir /B $*"
io.popen "doskey rm=del /q $*"
io.popen "doskey cat=more $*"
io.popen "doskey gs=git status"
io.popen "doskey ga=git add ."
io.popen "doskey gc=git commit -m $*"
io.popen "doskey gp=git push"
io.popen "doskey v=nvim"
io.popen "doskey sp=spotify_player"
io.popen "doskey rmdir=rmdir /q /s $*"
io.popen 'doskey touch=cmd.exe /c "echo. > $*"'
io.popen "doskey tu=wsl -d Ubuntu-20.04"
io.popen "doskey clear=cls"
io.popen "doskey aliases=nvim %LOCALAPPDATA%/nvim/lua/custom/aliases.lua"
io.popen "doskey inputrc=nvim %USERPROFILE%/.inputrc"
io.popen 'doskey clinkconfig=cmd /c "cd %LOCALAPPDATA%/clink && nvim"'
io.popen 'doskey esp-a3=wsl -d Ubuntu-20.04 bash -i -c "cd ~/espws23-a3-711 && nvim"'
io.popen 'doskey oop1-a1=wsl -d Ubuntu-20.04 bash -i -c "cd ~/oop1ss24-a1-530 && nvim"'
io.popen 'doskey oop1-a2=wsl -d Ubuntu-20.04 bash -i -c "cd ~/oop1ss24-a2-042 && nvim"'
io.popen "doskey reboot=shutdown /r -t 0"
io.popen 'doskey nvconfig=cmd /c "cd %LOCALAPPDATA%/nvim/lua/custom && nvim"'
io.popen 'doskey gdi=cmd /c "cd C:/Users/zachs/Projects/tugraz/GDI/gdi2023 && nvim"'
io.popen 'doskey battery=cmd /c "cd C:/Users/zachs/Projects/battery && nvim"'
io.popen 'doskey bcalc=cmd /c "cd C:/Users/zachs/Projects/b-calc && nvim"'
io.popen 'doskey fuzzy=cmd /c "cd C:/Users/zachs/Projects/fuzzy-disco && nvim"'
io.popen 'doskey tracksy=wsl bash -i -c "cd ~/Tracksy_BE && nvim"'
io.popen "doskey tugraz=cd C:/Users/zachs/Projects/tugraz"
